export const VEHICLES = [
    "50", "51", "52", "53", "55", "56", "58", "61", "62",
    "ダイヤ1", "ダイヤ2", "ダイヤ3"
];

export const DEFAULT_DRIVERS: Record<string, string> = {
    "50": "黒田",
    "52": "大池",
    "53": "市川",
    "55": "勝山",
    "56": "荒川",
    "58": "萩原",
    "61": "山口",
    "62": "細川",
    "51": "横山",
    "ダイヤ1": "南",
    "ダイヤ2": "竹原",
    "ダイヤ3": "古幡"
};

export const DRIVERS_LIST = [
    "黒田", "大池", "市川", "勝山", "荒川", "萩原", "山口", "細川", "横山", "南", "竹原", "古幡"
];

export const PICKUP_LOCATIONS = [
    { name: "新光", reading: "しんこう" },
    { name: "ヒラバヤシ", reading: "ひらばやし" },
    { name: "サンコーH", reading: "さんこーH" },
    { name: "ヤマカ", reading: "やまか" },
    { name: "回転", reading: "かいてん" },
    { name: "コーエー", reading: "こーえー" },
    { name: "黒田", reading: "くろだ" },
    { name: "伸和", reading: "しんわ" },
    { name: "GP", reading: "じーぴー" },
    { name: "新町", reading: "しんまち" },
    { name: "飯山F", reading: "いいやまF" },
    { name: "クマイ", reading: "くまい" },
    { name: "高松", reading: "たかまつ" },
    { name: "SE富士見", reading: "えすいーふじみ" },
    { name: "ダイドー", reading: "だいどー" },
    { name: "つるみね", reading: "つるみね" },
    { name: "豊科RC", reading: "とよしなRC" },
    { name: "弥生精工", reading: "やよいせいこう" },
    { name: "島田製作所", reading: "しまだせいさくしょ" },
    { name: "三全精工", reading: "さんぜんせいこう" },
    { name: "サンホタカ", reading: "さんほたか" },
    { name: "中村M", reading: "なかむらM" },
    { name: "オタリGAC", reading: "おたりGAC" },
    { name: "阿部電機", reading: "あべでんき" },
    { name: "ヤマカ精工", reading: "やまかせいこう" },
    { name: "内山精工", reading: "うちやませいこう" },
    { name: "猪又", reading: "いのまた" },
    { name: "トライアン", reading: "とらいあん" },
    { name: "サンコー", reading: "さんこー" },
    { name: "カワイ", reading: "かわい" },
    { name: "大和", reading: "やまと" },
    { name: "IHI大桑", reading: "IHIおおくわ" },
    { name: "IHI回転", reading: "IHIかいてん" },
    { name: "泉", reading: "いずみ" },
    { name: "猪俣", reading: "いのまた" },
    { name: "トーエネック", reading: "とーえねっく" },
    { name: "小林鋼材", reading: "こばやしこうざい" },
    { name: "信越ポリマ", reading: "しんえつぽりま" },
    { name: "清水口Fe", reading: "しみずぐちFe" },
    { name: "南安", reading: "なんあん" },
    { name: "しなのフジ", reading: "しなのふじ" },
    { name: "CMCS", reading: "CMCS" },
    { name: "一陽", reading: "いちよう" },
    { name: "ホーマー", reading: "ほーまー" },
    { name: "コパル", reading: "こぱる" },
    { name: "回転ホッパー", reading: "かいてんほっぱー" },
    { name: "富士電機", reading: "ふじでんき" },
    { name: "マクセルイズミ", reading: "まくせるいずみ" },
    { name: "協伸精機", reading: "きょうしんせいき" },
    { name: "黒田精工", reading: "くろだせいこう" },
    { name: "樫山工業", reading: "かしやまこうぎょう" },
    { name: "ＩＨＩ新町", reading: "IHIしんまち" },
    { name: "エプソン", reading: "えぷそん" },
    { name: "伸和精工", reading: "しんわせいこう" },
    { name: "金岡商店", reading: "かなおかしょうてん" },
    { name: "熊井製作所", reading: "くまいせいさくしょ" },
    { name: "サンコー・信州吉野", reading: "さんこー・しんしゅうよしの" },
    { name: "小谷デンソー", reading: "おたりでんそー" },
    { name: "パステック", reading: "ぱすてっく" },
    { name: "ハーモニックドライブ", reading: "はーもにっくどらいぶ" },
    { name: "高松工業", reading: "たかまつこうぎょう" },
    { name: "コーエー精機", reading: "こーえーせいき" },
    { name: "新光電気", reading: "しんこうでんき" },
    { name: "ＩＨＩエアロ", reading: "IHIえあろ" },
    { name: "市場", reading: "いちば" },
    { name: "安曇野本多通信", reading: "あずみのほんだつうしん" },
    { name: "カワイ精密", reading: "かわいせいみつ" },
    { name: "小松製作所", reading: "こまつせいさくしょ" },
    { name: "飯山富士", reading: "いいやまふじ" },
    { name: "中信製作所", reading: "ちゅうしんせいさくしょ" },
    { name: "柳原製作所", reading: "やなぎはらせいさくしょ" },
    { name: "アズミ村田製作所", reading: "あずみむらたせいさくしょ" },
    { name: "関根商店", reading: "せきねしょうてん" },
    { name: "ナカムラマジック（箕輪）", reading: "なかむらまじっく（みのわ）" },
    { name: "永井精機", reading: "ながいせいき" },
    { name: "臼居製作所", reading: "うすいせいさくしょ" },
    { name: "ヒラサワ", reading: "ひらさわ" },
    { name: "ハイラット", reading: "はいらっと" },
    { name: "信州タケエイ", reading: "しんしゅうたけえい" },
    { name: "アクトジャパン・ハセガワ", reading: "あくとじゃぱん・はせがわ" },
    { name: "日本電熱", reading: "にほんでんねつ" },
    { name: "積水プラ", reading: "せきすいぷら" },
    { name: "ユタカ", reading: "ゆたか" },
    { name: "大栄産業", reading: "だいえいさんぎょう" },
    { name: "中信高周波", reading: "ちゅうしんこうしゅうは" },
    { name: "松下金属工業", reading: "まつしたきんぞくこうぎょう" },
    { name: "大和興業", reading: "やまとこうぎょう" },
    { name: "日邦バルブ", reading: "にっぽうばるぶ" },
    { name: "松本リサイクル", reading: "まつもとりさいくる" },
    { name: "松下金属", reading: "まつしたきんぞく" },
    { name: "信越軽金属納品", reading: "しんえつけいきんぞくのうひん" },
    { name: "一陽鐵建社", reading: "いちようてっけんしゃ" },
    { name: "一之瀬製作所", reading: "いちのせせいさくしょ" },
    { name: "サンリン", reading: "さんりん" },
    { name: "原田商事", reading: "はらだしょうじ" },
    { name: "土屋製工", reading: "つちやせいこう" },
    { name: "トーシス", reading: "とーしす" },
    { name: "デンソー", reading: "でんそー" },
    { name: "コカ・コーラ", reading: "こか・こーら" },
    { name: "創悠遊", reading: "そうゆうゆう" },
    { name: "猪又鈑金", reading: "いのまたばんきん" },
    { name: "ハイライト", reading: "はいらいと" },
    { name: "フロンティア", reading: "ふろんてぃあ" },
    { name: "レゾナック大町", reading: "れぞなっくおおまち" },
    { name: "共立製作所", reading: "きょうりつせいさくしょ" },
    { name: "東信工業", reading: "とうしんこうぎょう" },
    { name: "日邦納品", reading: "にっぽうのうひん" },
    { name: "松澤製作所", reading: "まつざわせいさくしょ" },
    { name: "富士電機メーター", reading: "ふじでんきめーたー" },
    { name: "トライアン相互", reading: "とらいあんそうご" },
    { name: "エムケーシー", reading: "えむけーしー" },
    { name: "エムエートレーディング", reading: "えむえーとれーでぃんぐ" },
    { name: "エヌピーシー・ネハシ", reading: "えぬぴーしー・ねはし" },
    { name: "豊科リサイクル", reading: "とよしなりさいくる" },
    { name: "カイジョー", reading: "かいじょー" },
    { name: "優屋", reading: "ゆうや" },
    { name: "京セラ岡谷", reading: "きょうせらおかや" },
    { name: "ホタカリサイクル", reading: "ほたかりさいくる" },
    { name: "高山製作所", reading: "たかやませいさくしょ" },
    { name: "大町富士", reading: "おおまちふじ" },
    { name: "しなの富士通", reading: "しなのふじつう" },
    { name: "フロンティア納品", reading: "ふろんてぃあのうひん" },
    { name: "大和製作所", reading: "やまとせいさくしょ" },
    { name: "ユニフレ", reading: "ゆにふれ" },
    { name: "ミスズ工業", reading: "みすずこうぎょう" },
    { name: "ニッキトライシステム", reading: "にっきとらいしすてむ" },
    { name: "一ノ瀬鉄工", reading: "いちのせてっこう" },
    { name: "萩原商事", reading: "はぎわらしょうじ" },
    { name: "中電", reading: "ちゅうでん" },
    { name: "日穀製粉", reading: "にっこくせいふん" },
    { name: "レゾナック塩尻", reading: "れぞなっくしおじり" },
    { name: "木下工業", reading: "きのしたこうぎょう" },
    { name: "タキワ", reading: "たきわ" },
    { name: "アサハラ", reading: "あさはら" },
    { name: "カシマプレシジョン", reading: "かしまぷれしじょん" },
    { name: "倉科鉄工", reading: "くらしなてっこう" },
    { name: "キッツ茅野", reading: "きっつちの" },
    { name: "東電", reading: "とうでん" },
    { name: "フィット工業", reading: "ふぃっとこうぎょう" },
    { name: "あずさ環境", reading: "あずさかんきょう" },
    { name: "信越電装", reading: "しんえつでんそう" },
    { name: "テクノエフ", reading: "てくのえふ" },
    { name: "ヨーケン", reading: "よーけん" },
    { name: "東工シャッター", reading: "とうこうしゃったー" },
    { name: "清水口建設", reading: "しみずぐちけんせつ" },
    { name: "WAKO", reading: "WAKO" },
    { name: "コヤマ", reading: "こやま" },
    { name: "松岡産業", reading: "まつおかさんぎょう" },
    { name: "西電設", reading: "にしでんせつ" },
    { name: "東洋計器", reading: "とうようけいき" },
    { name: "嶋田製作所", reading: "しまだせいさくしょ" },
    { name: "フジ精密", reading: "ふじせいみつ" },
    { name: "アルミ工場", reading: "あるみこうじょう" },
    { name: "中野セメント", reading: "なかのせめんと" },
    { name: "カンノ", reading: "かんの" },
    { name: "東部金属", reading: "とうぶきんぞく" },
    { name: "平田商店", reading: "ひらたしょうてん" },
    { name: "レゾナック塩尻納品", reading: "れぞなっくしおじりのうひん" },
    { name: "庄内非鉄", reading: "しょうないひてつ" },
    { name: "明科リサイクル", reading: "あかしなりさいくる" },
    { name: "まるげん", reading: "まるげん" },
    { name: "高山商店", reading: "たかやましょうてん" },
    { name: "あずさ環境保全", reading: "あずさかんきょうほぜん" },
    { name: "オータックス", reading: "おーたっくす" }
];
